services:
  webservice:
    build:
      context: .
      dockerfile: ./bin/webserver/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./webroot:/var/www/html/
      - ./config/vhosts/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/apache2:/var/log/apache2
    ports:
      - "${HOST_MACHINE_HTTP_PORT}:80"

  mysql:
    image: "${DB_SERVER}"
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - ${HOST_MACHINE_MYSQL_PORT}:${HOST_MACHINE_MYSQL_PORT}
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${HOST_MACHINE_PHPMYADMIN_PORT}:80"